// src/components/core/details/person-details/PersonDetailsHeader.tsx
import React, { FC } from 'react';
import UiInfoHeader from '../../../ui/imfo-header/UiInfoHeader';
import { Person } from '../../../../types/Person';
import { arrayToString } from '../../../../utils/arrayToString.helper';
import useTranslation from 'next-translate/useTranslation';

interface Props {
  details: Person.RootObject;
}

const PersonDetailsHeader: FC<Props> = ({ details }) => {
  const { t } = useTranslation('details');

  return (
    <UiInfoHeader original_title={details.name} title={details.name} image={details.profile_path}>
      <li>
        {t('person_details.birthday')} <span>{new Date(details.birthday).toLocaleDateString()}</span>
      </li>
      {details.deathday && (
        <li>
          {t('person_details.deathday')} <span>{new Date(details.deathday).toLocaleDateString()}</span>
        </li>
      )}
      {details.place_of_birth && (
        <li>
          {t('person_details.place_of_birth')} <span>{details.place_of_birth}</span>
        </li>
      )}
      {details.known_for_department && (
        <li>
          {t('person_details.fame_for')} <span>{details.known_for_department}</span>
        </li>
      )}
      {details.also_known_as.length > 0 && (
        <li>
          {t('person_details.also_known_as')} <span>{arrayToString(details.also_known_as)}</span>
        </li>
      )}
    </UiInfoHeader>
  );
};

export default PersonDetailsHeader;

// apps/frontendVue/src/features/details/ui/personDetails/PersonDetailsHeader.vue
<script setup lang="ts">
import type { TmdbPersonType } from "@movie-tracker/types";
import { getTmdbImageUrl } from "~/utils/getTmdbImageUrl";
import UiInfoHeader from "~/components/ui/UiInfoHeader.vue";
import UiTypography from "~/components/ui/UiTypography.vue";
import { useI18n } from "#imports";
import { arrayToString } from "@movie-tracker/utils";

interface PersonDetailsHeaderProps {
  details?: TmdbPersonType | null;
}

const props = defineProps<PersonDetailsHeaderProps>()
const { locale } = useI18n();

</script>

<template>
  <UiInfoHeader
    :image="getTmdbImageUrl(props.details?.profile_path)"
    :title="props.details?.name ?? ''"
  >
    <UiTypography
      v-if="props.details?.birthday"
      as="li"
      variant="listItem"
    >
      {{ $t("details.birthday") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ new Date(props.details?.birthday || "").toLocaleDateString(locale) }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.deathday"
      as="li"
      variant="listItem"
    >
      {{ $t("details.deathday") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ new Date(props.details?.deathday || "").toLocaleDateString(locale) }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.place_of_birth"
      as="li"
      variant="listItem"
    >
      {{ $t("details.placeOfBirth") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ props.details?.place_of_birth }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.known_for_department"
      as="li"
      variant="listItem"
    >
      {{ $t("details.fameFor") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ props.details?.known_for_department }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.also_known_as?.length"
      as="li"
      variant="listItem"
    >
      {{ $t("details.alsoKnownAs") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ arrayToString(props.details?.also_known_as) }}
      </UiTypography>
    </UiTypography>
  </UiInfoHeader>
</template>

<style module lang="scss">
</style>
