// apps/frontendVue/src/features/details/ui/movieDetails/MovieDetailsProducers.vue
<script setup lang="ts">
import type { TmdbCreditsCastType, TmdbMediaDetailsCreatedByType } from "@movie-tracker/types";
import { NuxtLink } from "#components";
import { useLocalePath } from "#i18n";
import UiTypography from "~/components/ui/UiTypography.vue";

interface MovieDetailsProducersProps {
  producers: TmdbCreditsCastType[] | TmdbMediaDetailsCreatedByType[];
}

const props = defineProps<MovieDetailsProducersProps>();
const localePath = useLocalePath()

</script>

<template>
  <template
    v-for="(producer, index) in props.producers"
    :key="producer.id"
  >
    <UiTypography
      :as="NuxtLink"
      :to="localePath(`/details/person/${producer.id}`)"
      variant="linkUnderlined"
    >
      {{ producer.name }}
    </UiTypography>
    {{ index !== props.producers.length - 1 ? ', ' : '' }}
  </template>
</template>

// src/components/details-page/movie-details/MovieDetailsProducers.tsx
import React, { FC } from 'react';
import { Credits } from '@/types/Credits';
import { Details } from '@/types/Details';
import Link from 'next/link';
import { Typography } from '@/components/ui/typography/UiTypography';

interface Props {
  producers: Credits.Cast[] | Details.CreatedBy[];
}

const MovieDetailsProducers: FC<Props> = (props) => {
  return (
    <>
      {props.producers.map((el, index) => (
        <React.Fragment key={index}>
          <Typography as={Link} variant="linkUnderlined" href={`/details/person/${el.id}`}>
            {el.name}
          </Typography>
          {props.producers.length - 1 !== index && ', '}
        </React.Fragment>
      ))}
    </>
  );
};

export default MovieDetailsProducers;
