// apps/frontendVue/src/features/details/ui/personDetails/PersonDetailsHeader.vue
<script setup lang="ts">
import type { TmdbPersonType } from "@movie-tracker/types";
import { getTmdbImageUrl } from "~/utils/getTmdbImageUrl";
import UiInfoHeader from "~/components/ui/UiInfoHeader.vue";
import UiTypography from "~/components/ui/UiTypography.vue";
import { useI18n } from "#imports";
import { arrayToString } from "@movie-tracker/utils";

interface PersonDetailsHeaderProps {
  details?: TmdbPersonType | null;
}

const props = defineProps<PersonDetailsHeaderProps>()
const { locale } = useI18n();

</script>

<template>
  <UiInfoHeader
    :image="getTmdbImageUrl(props.details?.profile_path)"
    :title="props.details?.name ?? ''"
  >
    <UiTypography
      v-if="props.details?.birthday"
      as="li"
      variant="listItem"
    >
      {{ $t("details.birthday") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ new Date(props.details?.birthday || "").toLocaleDateString(locale) }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.deathday"
      as="li"
      variant="listItem"
    >
      {{ $t("details.deathday") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ new Date(props.details?.deathday || "").toLocaleDateString(locale) }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.place_of_birth"
      as="li"
      variant="listItem"
    >
      {{ $t("details.placeOfBirth") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ props.details?.place_of_birth }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.known_for_department"
      as="li"
      variant="listItem"
    >
      {{ $t("details.fameFor") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ props.details?.known_for_department }}
      </UiTypography>
    </UiTypography>

    <UiTypography
      v-if="props.details?.also_known_as?.length"
      as="li"
      variant="listItem"
    >
      {{ $t("details.alsoKnownAs") }}:
      <UiTypography
        as="span"
        variant="listItemValue"
      >
        {{ arrayToString(props.details?.also_known_as) }}
      </UiTypography>
    </UiTypography>
  </UiInfoHeader>
</template>

<style module lang="scss">
</style>

// src/components/details-page/person-details/PersonDetailsHeader.tsx
import { UiInfoHeader } from '@/components/ui/imfo-header/UiInfoHeader';
import { Person } from '@/types/Person';
import { arrayToString } from '@/utils/arrayToString';
import useTranslation from 'next-translate/useTranslation';
import { Typography } from '@/components/ui/typography/UiTypography';

interface PersonDetailsHeaderProps {
  details: Person.RootObject;
}

export const PersonDetailsHeader = (props: PersonDetailsHeaderProps) => {
  const { details } = props;
  const { t, lang } = useTranslation('details');

  return (
    <UiInfoHeader original_title={details.name} title={details.name} image={details.profile_path}>
      <li>
        {t('person_details.birthday')}{' '}
        <Typography as="span" variant="listItem">
          {new Date(details.birthday).toLocaleDateString(lang)}
        </Typography>
      </li>
      {details.deathday && (
        <li>
          {t('person_details.deathday')}{' '}
          <Typography as="span" variant="listItem">
            {new Date(details.deathday).toLocaleDateString(lang)}
          </Typography>
        </li>
      )}
      {details.place_of_birth && (
        <li>
          {t('person_details.place_of_birth')}{' '}
          <Typography as="span" variant="listItem">
            {details.place_of_birth}
          </Typography>
        </li>
      )}
      {details.known_for_department && (
        <li>
          {t('person_details.fame_for')}{' '}
          <Typography as="span" variant="listItem">
            {details.known_for_department}
          </Typography>
        </li>
      )}
      {!!details.also_known_as.length && (
        <li>
          {t('person_details.also_known_as')}{' '}
          <Typography as="span" variant="listItem">
            {arrayToString(details.also_known_as)}
          </Typography>
        </li>
      )}
    </UiInfoHeader>
  );
};
